require 'sinatra/activerecord'
require 'sinatra/activerecord/rake'


task :clean do
  cleanup
end

task :build => :clean do
  compass
  javascript
end

task :server do
  server
end

task :migrate do
  migrate
  init_tongue_twister
end

task :flickr do
  get_flickr_pin
end

def cleanup
  sh 'rm -rf public/js/*'
  sh 'rm -rf public/css/*'
end

def compass(opts = '')
  sh 'compass compile -c config.ru --force ' + opts
end

def javascript
  sh 'cp assets/js/* public/js/'
end

def server
  sh 'ruby app.rb -e development'
end

def migrate(env = 'development')
  if env == 'development'
    sh 'rm -rf ./db/schema.rb'
    sh 'rm -rf ./db/development.rb'
    sh 'bundle exec rake db:migrate'
    sh 'bundle exec rake db:create_migration NAME=create_tongue_twisters'
  elif env == 'production'
  end
end

def init_tongue_twister
  sh 'ruby ./../resources/csv/init_tongue_twister.rb'
end

def get_flickr_pin(env = 'development')
  require 'flickraw'

  flickr_config = YAML.load_file('config/flickr.yml')
  flickr_config = flickr_config[env]

  FlickRaw.api_key = flickr_config['key']
  FlickRaw.shared_secret = flickr_config['secret']

  token = flickr.get_request_token
  auth_url = flickr.get_authorize_url(token['oauth_token'], :perms => 'delete')
  sh "open #{auth_url}"
  puts "input pin:"
  pin = STDIN.gets

  verify = pin.strip
  flickr.get_access_token(token['oauth_token'], token['oauth_token_secret'], verify)
  login = flickr.test.login
  puts 'access_token:' + flickr.access_token
  puts 'access_secret:' + flickr.access_secret
end
