require 'sinatra/activerecord'
require 'sinatra/activerecord/rake'


task :clean do
  cleanup
end

task :build => :clean do
  compass
  javascript
end

task :server do
  server
end

task :migrate do
  migrate
  init_tongue_twister
end

def cleanup
  sh 'rm -rf public/js/*'
  sh 'rm -rf public/css/*'
end

def compass(opts = '')
  sh 'compass compile -c config.ru --force ' + opts
end

def javascript
  sh 'cp assets/js/* public/js/'
end

def server
  sh 'ruby app.rb -e development'
end

def migrate
  sh 'rm -rf ./db/schema.rb'
  sh 'rm -rf ./db/development.rb'
  sh 'bundle exec rake db:migrate'
  sh 'bundle exec rake db:create_migration NAME=create_tongue_twisters'
end

def init_tongue_twister
  sh 'ruby ./../resources/csv/init_tongue_twister.rb'
end
