require 'sinatra/activerecord'
require 'sinatra/activerecord/rake'


task :clean do
  cleanup
end

task :build => :clean do
  compass
  javascript
end

task :server do
  server
end

task :migrate do
  migrate
  init_record_title
end

def cleanup
  sh 'rm -rf public/js/*'
  sh 'rm -rf public/css/*'
end

def compass(opts = '')
  sh 'compass compile -c config.ru --force ' + opts
end

def javascript
  sh 'cp assets/js/* public/js/'
end

def server
  sh 'ruby app.rb -e development'
end

def migrate(env = 'development')
  if env == 'development'
    sh 'bundle exec rake db:migrate'
    sh 'bundle exec rake db:create_migration NAME=create_users'
    sh 'bundle exec rake db:create_migration NAME=create_records'
    sh 'bundle exec rake db:create_migration NAME=create_record_titles'
    sh 'bundle exec rake db:create_migration NAME=create_record_comments'
  elsif env == 'production'
  end
end

def init_record_title
  sh 'ruby ./../resources/csv/init_record_title.rb'
end
